// Preset Tailwind classes exposed in the playground className dropdown.
// This file is scanned by Tailwind via `@source` in globals.css, so the
// strings below always get compiled into the CSS bundle.

export const presetClassNames = [
  "text-red-500",
  "text-orange-500",
  "text-amber-500",
  "text-yellow-500",
  "text-lime-500",
  "text-green-500",
  "text-emerald-500",
  "text-teal-500",
  "text-cyan-500",
  "text-sky-500",
  "text-blue-500",
  "text-indigo-500",
  "text-violet-500",
  "text-purple-500",
  "text-fuchsia-500",
  "text-pink-500",
  "text-rose-500",
  "text-neutral-50",
  "text-neutral-900",
  "font-thin",
  "font-extralight",
  "font-light",
  "font-normal",
  "font-medium",
  "font-semibold",
  "font-bold",
  "font-extrabold",
  "font-black",
  "text-xs",
  "text-sm",
  "text-base",
  "text-lg",
  "text-xl",
  "text-2xl",
  "text-3xl",
  "text-4xl",
  "text-5xl",
  "text-6xl",
  "text-7xl",
  "text-8xl",
  "uppercase",
  "lowercase",
  "capitalize",
  "italic",
  "tracking-tight",
  "tracking-wide",
  "tracking-widest",
  "opacity-50",
  "opacity-75",
  "opacity-90",
  "bg-red-500",
  "bg-blue-500",
  "bg-emerald-500",
  "bg-neutral-900",
  "bg-neutral-50",
  "p-2",
  "p-4",
  "p-6",
  "p-8",
  "px-4 py-2",
  "rounded",
  "rounded-md",
  "rounded-lg",
  "rounded-xl",
  "rounded-full",
  "shadow-md",
  "shadow-lg",
  "shadow-xl",
] as const;
