import { execFile } from "child_process";
import { promises as fs } from "fs";
import path from "path";
import { promisify } from "util";
import { format } from "prettier";
import { rimraf } from "rimraf";
import {
  registryItemSchema,
  registrySchema,
  type Registry,
} from "shadcn/registry";
import { z } from "zod";

import { blocks } from "../registry/registry-blocks";
import { examples } from "../registry/registry-examples";
import { lib } from "../registry/registry-lib";
import { ui } from "../registry/registry-ui";

type RegistryItem = Registry["items"][number];
type RegistryFile = NonNullable<RegistryItem["files"]>[number];
type RegistryFileMap = Map<string, RegistryFile>;

const execFileAsync = promisify(execFile);
const DEPRECATED_ITEMS = new Set(["toast"]);
const VERBOSE = process.env.REGISTRY_VERBOSE === "true";

function log(message: string, ...args: unknown[]): void {
  if (VERBOSE) {
    console.log(message, ...args);
  }
}

function info(message: string, ...args: unknown[]): void {
  console.log(message, ...args);
}

function normalizePath(filePath: string): string {
  return filePath.replace(/\\/g, "/");
}

function normalizeRegistryFile(file: RegistryFile): RegistryFile {
  const normalizedFile = {
    ...file,
    path: normalizePath(file.path),
    ...(file.target ? { target: normalizePath(file.target) } : {}),
  } satisfies RegistryFile;

  return normalizedFile;
}

function normalizeRegistryItem(item: RegistryItem): RegistryItem {
  return {
    ...item,
    files: item.files?.map(normalizeRegistryFile),
  };
}

function mergeFiles(files: RegistryFile[] | undefined): RegistryFile[] {
  const normalizedFiles: RegistryFileMap = new Map();

  for (const file of files ?? []) {
    const normalizedFile = normalizeRegistryFile(file);
    const existingFile = normalizedFiles.get(normalizedFile.path);

    if (
      !existingFile ||
      (normalizedFile.content &&
        (!existingFile.content || existingFile.target === ""))
    ) {
      normalizedFiles.set(normalizedFile.path, normalizedFile);
    }
  }

  return Array.from(normalizedFiles.values());
}

function deduplicateItemFiles(item: RegistryItem): RegistryItem {
  return {
    ...item,
    files: mergeFiles(item.files),
  };
}

function deduplicateRegistryItems(items: Registry["items"]): Registry["items"] {
  const uniqueItemsByName = new Map<string, RegistryItem>();

  for (const item of items) {
    const dedupedItem = deduplicateItemFiles(item);
    const existingItem = uniqueItemsByName.get(item.name);

    if (!existingItem) {
      uniqueItemsByName.set(item.name, dedupedItem);
      continue;
    }

    uniqueItemsByName.set(item.name, {
      ...existingItem,
      ...dedupedItem,
      files: mergeFiles([
        ...(existingItem.files ?? []),
        ...(dedupedItem.files ?? []),
      ]),
    });
  }

  return Array.from(uniqueItemsByName.values());
}

function createRegistry(): Registry {
  const items = [
    {
      name: "index",
      type: "registry:style",
      dependencies: [
        "tw-animate-css",
        "class-variance-authority",
        "lucide-react",
      ],
      registryDependencies: ["utils"],
      cssVars: {},
      files: [],
    },
    ...ui,
    ...examples,
    ...lib,
    ...blocks,
  ].filter((item) => !DEPRECATED_ITEMS.has(item.name));

  const normalizedItems = deduplicateRegistryItems(
    z.array(registryItemSchema).parse(items).map(normalizeRegistryItem),
  );

  return registrySchema.parse({
    name: "shadcn/ui",
    homepage: "https://ui.shadcn.com",
    items: normalizedItems,
  });
}

const registry = createRegistry();

async function formatGeneratedFile(
  filePath: string,
  content: string,
): Promise<string> {
  return format(content, { filepath: filePath });
}

async function writeJson(filePath: string, data: unknown): Promise<void> {
  const json = `${JSON.stringify(data, null, 2)}\n`;
  await fs.writeFile(filePath, await formatGeneratedFile(filePath, json));
}

function getRegistryComponentImport(item: RegistryItem): string | null {
  const componentPath = item.files?.[0]?.path;
  return componentPath
    ? `@/${normalizePath(componentPath).replace(/\.(tsx|ts)$/, "")}`
    : null;
}

async function buildRegistryIndex(): Promise<void> {
  log("Building registry index");

  let index = `// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

type RegistryComponent = React.ComponentType<Record<string, never>>
type RegistryModule = Record<string, unknown>
type RegistryEntry = {
  name: string
  description: string
  type: string
  registryDependencies?: string[]
  files: Array<{ path: string; type: string }>
  component: React.LazyExoticComponent<RegistryComponent> | null
  meta?: Record<string, unknown>
}

function isRegistryComponent(value: unknown): value is RegistryComponent {
  return typeof value === "function" || (typeof value === "object" && value !== null)
}

function pickRegistryComponent(mod: RegistryModule, fallbackName: string): RegistryComponent {
  const exportName = Object.keys(mod).find((key) => isRegistryComponent(mod[key]))
  const candidate = mod.default ?? mod[exportName ?? fallbackName]

  if (isRegistryComponent(candidate)) {
    return candidate
  }

  return function MissingRegistryComponent() {
    return null
  }
}

export const Index: Record<string, RegistryEntry> = {`;

  for (const item of registry.items) {
    if (!item.files || item.files.length === 0) {
      log(`Skipping "${item.name}" because it has no files`);
      continue;
    }

    const componentPath = getRegistryComponentImport(item);

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: ${JSON.stringify(item.description ?? "")},
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files
      .map((file) => {
        const filePath = normalizePath(file.path);
        return `{
      path: "${filePath}",
      type: "${file.type}",
    }`;
      })
      .join(", ")}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}") as RegistryModule
      return { default: pickRegistryComponent(mod, "${item.name}") }
    })`
        : "null"
    },
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
}`;

  const outPath = path.join(process.cwd(), "__registry__/index.tsx");
  await rimraf(outPath);
  await fs.writeFile(outPath, await formatGeneratedFile(outPath, index));
}

async function buildRegistryJsonFile(): Promise<void> {
  log("Writing root registry files");

  const rootJson = path.join(process.cwd(), "registry.json");
  const publicJson = path.join(process.cwd(), "public/registry.json");

  await Promise.all([rimraf(rootJson), rimraf(publicJson)]);
  await Promise.all([
    writeJson(rootJson, registry),
    writeJson(publicJson, registry),
  ]);
}

async function buildShadcnRegistry(): Promise<void> {
  const shadcnBin = path.join(
    process.cwd(),
    "node_modules",
    ".bin",
    process.platform === "win32" ? "shadcn.cmd" : "shadcn",
  );
  const args = ["shadcn", "registry:build"];

  if (VERBOSE) {
    args.push("--verbose");
  }

  try {
    const { stdout, stderr } = await execFileAsync(shadcnBin, args.slice(1), {
      maxBuffer: 1024 * 1024 * 20,
    });

    log(stdout);
    log(stderr);
  } catch (error) {
    console.error("shadcn registry build failed:", error);
    throw error;
  }
}

async function repairGeneratedRegistryJson(): Promise<void> {
  const publicRJson = path.join(process.cwd(), "public/r/registry.json");
  const publicRDir = path.join(process.cwd(), "public/r");
  const publicJson = path.join(process.cwd(), "public/registry.json");

  const registryJsonContent = await fs.readFile(publicRJson, "utf8");
  const generatedRegistry = registrySchema.parse(
    JSON.parse(registryJsonContent),
  );
  const dedupedItems = deduplicateRegistryItems(generatedRegistry.items);
  const repairedRegistry = registrySchema.parse({
    ...generatedRegistry,
    items: dedupedItems,
  });

  await Promise.all([
    writeJson(publicRJson, repairedRegistry),
    writeJson(publicJson, repairedRegistry),
  ]);

  const files = await fs.readdir(publicRDir);

  await Promise.all(
    files
      .filter((file) => file.endsWith(".json") && file !== "registry.json")
      .map(async (file) => {
        const componentPath = path.join(publicRDir, file);
        const componentContent = await fs.readFile(componentPath, "utf8");
        const componentData = registryItemSchema.parse(
          JSON.parse(componentContent),
        );
        const fixedComponent = deduplicateItemFiles(componentData);

        await writeJson(componentPath, fixedComponent);
      }),
  );
}

(async () => {
  try {
    info(`Building ${registry.items.length} registry items`);
    await buildRegistryIndex();
    await buildRegistryJsonFile();
    await buildShadcnRegistry();
    await repairGeneratedRegistryJson();
    info("Registry build complete");
  } catch (error) {
    console.error("Registry build failed:", error);
    process.exit(1);
  }
})();
