#!/usr/bin/env node
/**
 * ensure-pro-obf — guarantee app/pro-obf.css exists.
 *
 * app/layout.tsx imports "./pro-obf.css" so Pro-block previews can pick up
 * the obfuscated class rules in production. But that file is generated by
 * scripts/obfuscate-pro.mjs and gitignored, so a fresh clone hitting
 * `pnpm dev` would otherwise die on an unresolvable import.
 *
 * This writes an empty stub (just a `@reference "./globals.css";`) when
 * the file is missing — fast, idempotent, and does not override a real
 * build. Hooked as `predev` in package.json.
 *
 * `pnpm build` always runs the full obfuscator and overwrites this stub.
 */

import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const CSS_OUT = join(process.cwd(), "app/pro-obf.css");

const STUB =
  "/* STUB — the real file is written by scripts/obfuscate-pro.mjs during\n" +
  " * `pnpm build`. This stub lets dev builds compile without a prior build. */\n" +
  '@reference "./globals.css";\n';

if (existsSync(CSS_OUT)) {
  process.exit(0);
}

writeFileSync(CSS_OUT, STUB);
console.log("  wrote stub app/pro-obf.css (regenerated by `pnpm build`)");
