// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react";

type RegistryComponent = React.ComponentType<Record<string, never>>;
type RegistryModule = Record<string, unknown>;
type RegistryEntry = {
  name: string;
  description: string;
  type: string;
  registryDependencies?: string[];
  files: Array<{ path: string; type: string }>;
  component: React.LazyExoticComponent<RegistryComponent> | null;
  meta?: Record<string, unknown>;
};

function isRegistryComponent(value: unknown): value is RegistryComponent {
  return (
    typeof value === "function" || (typeof value === "object" && value !== null)
  );
}

function pickRegistryComponent(
  mod: RegistryModule,
  fallbackName: string,
): RegistryComponent {
  const exportName = Object.keys(mod).find((key) =>
    isRegistryComponent(mod[key]),
  );
  const candidate = mod.default ?? mod[exportName ?? fallbackName];

  if (isRegistryComponent(candidate)) {
    return candidate;
  }

  return function MissingRegistryComponent() {
    return null;
  };
}

export const Index: Record<string, RegistryEntry> = {
  "animated-code-block": {
    name: "animated-code-block",
    description:
      "A code display component with real-time typing effects. Supports syntax highlighting and customizable themes.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/animated-code-block.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/animated-code-block"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "animated-code-block") };
    }),
    meta: undefined,
  },
  "animated-grainy-bg": {
    name: "animated-grainy-bg",
    description:
      "A dynamic animated gradient background component that supports various gradient patterns and animations.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/animated-grainy-bg.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/animated-grainy-bg"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "animated-grainy-bg") };
    }),
    meta: undefined,
  },
  "animated-text": {
    name: "animated-text",
    description:
      "A versatile text animation component that offers multiple animation types. Perfect for adding dynamic text effects to your UI.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/animated-text.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/animated-text"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "animated-text") };
    }),
    meta: undefined,
  },
  "bubble-background": {
    name: "bubble-background",
    description:
      "An interactive fluid bubble background component with animated colorful blobs that respond to user interaction.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/bubble-background.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/bubble-background"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "bubble-background") };
    }),
    meta: undefined,
  },
  "cyberpunk-card": {
    name: "cyberpunk-card",
    description:
      "A card component with a cyberpunk aesthetic. Features neon colors and a futuristic design.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/cyberpunk-card.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/cyberpunk-card"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "cyberpunk-card") };
    }),
    meta: undefined,
  },
  "dynamic-ripple": {
    name: "dynamic-ripple",
    description:
      "A ripple effect component that follows the cursor and can be customized with various options.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/dynamic-ripple.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/dynamic-ripple"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "dynamic-ripple") };
    }),
    meta: undefined,
  },
  "github-repo-card": {
    name: "github-repo-card",
    description:
      "A card component that displays information about a GitHub repository. It includes the repository name, description, stars, forks, and a link to the repository.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/github-repo-card.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/github-repo-card"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "github-repo-card") };
    }),
    meta: undefined,
  },
  "glitch-button": {
    name: "glitch-button",
    description:
      "Cyberpunk-inspired button with dynamic glitch effects that can be triggered on hover or click.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/glitch-button.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/glitch-button"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "glitch-button") };
    }),
    meta: undefined,
  },
  keyboard: {
    name: "keyboard",
    description: "A keyboard component that simulates a physical keyboard.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/keyboard.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import("@/registry/ui/keyboard")) as RegistryModule;
      return { default: pickRegistryComponent(mod, "keyboard") };
    }),
    meta: undefined,
  },
  "ms-paint": {
    name: "ms-paint",
    description:
      "A customizable drawing canvas component with paint-like interface.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/ms-paint.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import("@/registry/ui/ms-paint")) as RegistryModule;
      return { default: pickRegistryComponent(mod, "ms-paint") };
    }),
    meta: undefined,
  },
  "lamp-heading": {
    name: "lamp-heading",
    description: "A heading component with a lamp effect.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/lamp-heading.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/lamp-heading"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "lamp-heading") };
    }),
    meta: undefined,
  },
  "liquid-metal-button": {
    name: "liquid-metal-button",
    description: "A button component with a liquid metal effect.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/liquid-metal-button.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/liquid-metal-button"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "liquid-metal-button") };
    }),
    meta: undefined,
  },
  "image-comparison": {
    name: "image-comparison",
    description:
      "A image comparison component that allows users to compare images.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/image-comparison.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/image-comparison"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "image-comparison") };
    }),
    meta: undefined,
  },
  "image-scanner": {
    name: "image-scanner",
    description: "A image scanner component that allows users to scan images.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/image-scanner.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/image-scanner"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "image-scanner") };
    }),
    meta: undefined,
  },
  "glow-card": {
    name: "glow-card",
    description: "A glow card that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/glow-card.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import("@/registry/ui/glow-card")) as RegistryModule;
      return { default: pickRegistryComponent(mod, "glow-card") };
    }),
    meta: undefined,
  },
  marquee: {
    name: "marquee",
    description: "A customizable, interactive scrolling marquee component.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/marquee.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import("@/registry/ui/marquee")) as RegistryModule;
      return { default: pickRegistryComponent(mod, "marquee") };
    }),
    meta: undefined,
  },
  "matrix-code-rain": {
    name: "matrix-code-rain",
    description: "A matrix code rain that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/matrix-code-rain.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/matrix-code-rain"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "matrix-code-rain") };
    }),
    meta: undefined,
  },
  "morphing-blob": {
    name: "morphing-blob",
    description: "A morphing blob that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/morphing-blob.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/morphing-blob"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "morphing-blob") };
    }),
    meta: undefined,
  },
  "music-player": {
    name: "music-player",
    description: "A music player that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/music-player.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/music-player"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "music-player") };
    }),
    meta: undefined,
  },
  "reveal-card": {
    name: "reveal-card",
    description: "A reveal card that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/reveal-card.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import("@/registry/ui/reveal-card")) as RegistryModule;
      return { default: pickRegistryComponent(mod, "reveal-card") };
    }),
    meta: undefined,
  },
  "scroll-animation-trigger": {
    name: "scroll-animation-trigger",
    description:
      "A scroll animation trigger that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/scroll-animation-trigger.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/scroll-animation-trigger"
      )) as RegistryModule;
      return {
        default: pickRegistryComponent(mod, "scroll-animation-trigger"),
      };
    }),
    meta: undefined,
  },
  terminal: {
    name: "terminal",
    description: "A terminal that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/terminal.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import("@/registry/ui/terminal")) as RegistryModule;
      return { default: pickRegistryComponent(mod, "terminal") };
    }),
    meta: undefined,
  },
  "water-ripple-effect": {
    name: "water-ripple-effect",
    description: "A water ripple effect that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/water-ripple-effect.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/water-ripple-effect"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "water-ripple-effect") };
    }),
    meta: undefined,
  },
  "custom-cursor": {
    name: "custom-cursor",
    description: "A custom cursor that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/custom-cursor.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/custom-cursor"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "custom-cursor") };
    }),
    meta: undefined,
  },
  "apple-glass-effect": {
    name: "apple-glass-effect",
    description: "A apple glass effect that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/apple-glass-effect.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/apple-glass-effect"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "apple-glass-effect") };
    }),
    meta: undefined,
  },
  "3d-layered-card": {
    name: "3d-layered-card",
    description: "A 3D layered card that that provide several effects.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/3d-layered-card.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/ui/3d-layered-card"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "3d-layered-card") };
    }),
    meta: undefined,
  },
  "animated-code-block-demo": {
    name: "animated-code-block-demo",
    description: "Example showing a code block with typing animation effects.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/animated-code-block"],
    files: [
      {
        path: "registry/example/animated-code-block-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/animated-code-block-demo"
      )) as RegistryModule;
      return {
        default: pickRegistryComponent(mod, "animated-code-block-demo"),
      };
    }),
    meta: undefined,
  },
  "animated-grainy-bg-demo": {
    name: "animated-grainy-bg-demo",
    description: "Example showing an animated grainy background.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/animated-grainy-bg"],
    files: [
      {
        path: "registry/example/animated-grainy-bg-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/animated-grainy-bg-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "animated-grainy-bg-demo") };
    }),
    meta: undefined,
  },
  "animated-text-demo": {
    name: "animated-text-demo",
    description: "Example showing various text animations.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/animated-text.json"],
    files: [
      {
        path: "registry/example/animated-text-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/animated-text-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "animated-text-demo") };
    }),
    meta: undefined,
  },
  "bubble-background-demo": {
    name: "bubble-background-demo",
    description: "Example showing an interactive fluid background.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/bubble-background.json"],
    files: [
      {
        path: "registry/example/bubble-background-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/bubble-background-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "bubble-background-demo") };
    }),
    meta: undefined,
  },
  "cyberpunk-card-demo": {
    name: "cyberpunk-card-demo",
    description: "Example showing a cyberpunk card.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/cyberpunk-card.json"],
    files: [
      {
        path: "registry/example/cyberpunk-card-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/cyberpunk-card-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "cyberpunk-card-demo") };
    }),
    meta: undefined,
  },
  "cyberpunk-card-demo1": {
    name: "cyberpunk-card-demo1",
    description: "Example showing a cyberpunk card.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/cyberpunk-card.json"],
    files: [
      {
        path: "registry/example/cyberpunk-card-demo1.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/cyberpunk-card-demo1"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "cyberpunk-card-demo1") };
    }),
    meta: undefined,
  },
  "dynamic-ripple-demo": {
    name: "dynamic-ripple-demo",
    description: "Example showing a dynamic ripple effect.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/dynamic-ripple.json"],
    files: [
      {
        path: "registry/example/dynamic-ripple-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/dynamic-ripple-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "dynamic-ripple-demo") };
    }),
    meta: undefined,
  },
  "github-repo-card-demo": {
    name: "github-repo-card-demo",
    description: "Example showing a GitHub repo card.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/github-repo-card.json"],
    files: [
      {
        path: "registry/example/github-repo-card-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/github-repo-card-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "github-repo-card-demo") };
    }),
    meta: undefined,
  },
  "github-repo-card-demo1": {
    name: "github-repo-card-demo1",
    description: "Example showing a GitHub repo card.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/github-repo-card.json"],
    files: [
      {
        path: "registry/example/github-repo-card-demo1.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/github-repo-card-demo1"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "github-repo-card-demo1") };
    }),
    meta: undefined,
  },
  "github-repo-card-demo2": {
    name: "github-repo-card-demo2",
    description: "Example showing a GitHub repo card.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/github-repo-card.json"],
    files: [
      {
        path: "registry/example/github-repo-card-demo2.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/github-repo-card-demo2"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "github-repo-card-demo2") };
    }),
    meta: undefined,
  },
  "glitch-button-demo": {
    name: "glitch-button-demo",
    description: "Example showing a glitch button.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/glitch-button.json"],
    files: [
      {
        path: "registry/example/glitch-button-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/glitch-button-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "glitch-button-demo") };
    }),
    meta: undefined,
  },
  "keyboard-demo": {
    name: "keyboard-demo",
    description: "Example showing a interactive keyboard.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/keyboard.json"],
    files: [
      {
        path: "registry/example/keyboard-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/keyboard-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "keyboard-demo") };
    }),
    meta: undefined,
  },
  "keyboard-demo1": {
    name: "keyboard-demo1",
    description: "Example showing a interactive keyboard.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/keyboard.json"],
    files: [
      {
        path: "registry/example/keyboard-demo1.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/keyboard-demo1"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "keyboard-demo1") };
    }),
    meta: undefined,
  },
  "ms-paint-demo": {
    name: "ms-paint-demo",
    description: "Example showing a MS Paint clone.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/ms-paint.json"],
    files: [
      {
        path: "registry/example/ms-paint-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/ms-paint-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "ms-paint-demo") };
    }),
    meta: undefined,
  },
  "lamp-heading-demo": {
    name: "lamp-heading-demo",
    description: "Example showing a lamp heading.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/lamp-heading.json"],
    files: [
      {
        path: "registry/example/lamp-heading-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/lamp-heading-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "lamp-heading-demo") };
    }),
    meta: undefined,
  },
  "liquid-metal-button-demo": {
    name: "liquid-metal-button-demo",
    description: "Example showing a liquid metal button.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/liquid-metal-button.json"],
    files: [
      {
        path: "registry/example/liquid-metal-button-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/liquid-metal-button-demo"
      )) as RegistryModule;
      return {
        default: pickRegistryComponent(mod, "liquid-metal-button-demo"),
      };
    }),
    meta: undefined,
  },
  "image-comparison-demo": {
    name: "image-comparison-demo",
    description: "Example showing a image comparison.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/image-comparison.json"],
    files: [
      {
        path: "registry/example/image-comparison-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/image-comparison-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "image-comparison-demo") };
    }),
    meta: undefined,
  },
  "image-scanner-demo": {
    name: "image-scanner-demo",
    description: "Example showing a image scanner.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/image-scanner.json"],
    files: [
      {
        path: "registry/example/image-scanner-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/image-scanner-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "image-scanner-demo") };
    }),
    meta: undefined,
  },
  "image-scanner-demo1": {
    name: "image-scanner-demo1",
    description: "Example showing a image scanner.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/image-scanner.json"],
    files: [
      {
        path: "registry/example/image-scanner-demo1.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/image-scanner-demo1"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "image-scanner-demo1") };
    }),
    meta: undefined,
  },
  "glow-card-demo": {
    name: "glow-card-demo",
    description: "Example showing a glow card.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/glow-card.json"],
    files: [
      {
        path: "registry/example/glow-card-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/glow-card-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "glow-card-demo") };
    }),
    meta: undefined,
  },
  "glow-card-demo1": {
    name: "glow-card-demo1",
    description: "Example showing a glow card.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/glow-card.json"],
    files: [
      {
        path: "registry/example/glow-card-demo1.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/glow-card-demo1"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "glow-card-demo1") };
    }),
    meta: undefined,
  },
  "marquee-demo": {
    name: "marquee-demo",
    description: "Example showing a marquee.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/marquee.json"],
    files: [
      {
        path: "registry/example/marquee-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/marquee-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "marquee-demo") };
    }),
    meta: undefined,
  },
  "marquee-demo1": {
    name: "marquee-demo1",
    description: "Example showing a marquee.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/marquee.json"],
    files: [
      {
        path: "registry/example/marquee-demo1.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/marquee-demo1"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "marquee-demo1") };
    }),
    meta: undefined,
  },
  "marquee-demo2": {
    name: "marquee-demo2",
    description: "Example showing a marquee.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/marquee.json"],
    files: [
      {
        path: "registry/example/marquee-demo2.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/marquee-demo2"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "marquee-demo2") };
    }),
    meta: undefined,
  },
  "matrix-code-rain-demo": {
    name: "matrix-code-rain-demo",
    description: "Example showing a matrix code rain.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/matrix-code-rain.json"],
    files: [
      {
        path: "registry/example/matrix-code-rain-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/matrix-code-rain-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "matrix-code-rain-demo") };
    }),
    meta: undefined,
  },
  "morphing-blob-demo": {
    name: "morphing-blob-demo",
    description: "Example showing a morphing blob.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/morphing-blob.json"],
    files: [
      {
        path: "registry/example/morphing-blob-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/morphing-blob-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "morphing-blob-demo") };
    }),
    meta: undefined,
  },
  "music-player-demo": {
    name: "music-player-demo",
    description: "Example showing a music player.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/music-player.json"],
    files: [
      {
        path: "registry/example/music-player-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/music-player-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "music-player-demo") };
    }),
    meta: undefined,
  },
  "music-player-demo1": {
    name: "music-player-demo1",
    description: "Example showing a music player.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/music-player.json"],
    files: [
      {
        path: "registry/example/music-player-demo1.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/music-player-demo1"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "music-player-demo1") };
    }),
    meta: undefined,
  },
  "music-player-demo2": {
    name: "music-player-demo2",
    description: "Example showing a music player.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/music-player.json"],
    files: [
      {
        path: "registry/example/music-player-demo2.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/music-player-demo2"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "music-player-demo2") };
    }),
    meta: undefined,
  },
  "reveal-card-demo": {
    name: "reveal-card-demo",
    description: "Example showing a reveal card.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/reveal-card.json"],
    files: [
      {
        path: "registry/example/reveal-card-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/reveal-card-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "reveal-card-demo") };
    }),
    meta: undefined,
  },
  "scroll-animation-trigger-demo": {
    name: "scroll-animation-trigger-demo",
    description: "Example showing a scroll animation trigger.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/scroll-animation-trigger.json"],
    files: [
      {
        path: "registry/example/scroll-animation-trigger-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/scroll-animation-trigger-demo"
      )) as RegistryModule;
      return {
        default: pickRegistryComponent(mod, "scroll-animation-trigger-demo"),
      };
    }),
    meta: undefined,
  },
  "scroll-animation-trigger-demo1": {
    name: "scroll-animation-trigger-demo1",
    description: "Example showing a scroll animation trigger.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/scroll-animation-trigger.json"],
    files: [
      {
        path: "registry/example/scroll-animation-trigger-demo1.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/scroll-animation-trigger-demo1"
      )) as RegistryModule;
      return {
        default: pickRegistryComponent(mod, "scroll-animation-trigger-demo1"),
      };
    }),
    meta: undefined,
  },
  "scroll-animation-trigger-demo2": {
    name: "scroll-animation-trigger-demo2",
    description: "Example showing a scroll animation trigger.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/scroll-animation-trigger.json"],
    files: [
      {
        path: "registry/example/scroll-animation-trigger-demo2.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/scroll-animation-trigger-demo2"
      )) as RegistryModule;
      return {
        default: pickRegistryComponent(mod, "scroll-animation-trigger-demo2"),
      };
    }),
    meta: undefined,
  },
  "terminal-demo": {
    name: "terminal-demo",
    description: "Example showing a terminal.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/terminal.json"],
    files: [
      {
        path: "registry/example/terminal-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/terminal-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "terminal-demo") };
    }),
    meta: undefined,
  },
  "terminal-demo1": {
    name: "terminal-demo1",
    description: "Example showing a terminal.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/terminal.json"],
    files: [
      {
        path: "registry/example/terminal-demo1.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/terminal-demo1"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "terminal-demo1") };
    }),
    meta: undefined,
  },
  "water-ripple-effect-demo": {
    name: "water-ripple-effect-demo",
    description: "Example showing a water ripple effect.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/water-ripple-effect.json"],
    files: [
      {
        path: "registry/example/water-ripple-effect-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/water-ripple-effect-demo"
      )) as RegistryModule;
      return {
        default: pickRegistryComponent(mod, "water-ripple-effect-demo"),
      };
    }),
    meta: undefined,
  },
  "custom-cursor-demo": {
    name: "custom-cursor-demo",
    description: "Example showing a custom cursor.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/custom-cursor.json"],
    files: [
      {
        path: "registry/example/custom-cursor-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/custom-cursor-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "custom-cursor-demo") };
    }),
    meta: undefined,
  },
  "apple-glass-effect-demo": {
    name: "apple-glass-effect-demo",
    description: "Example showing an Apple Glass Effect.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/apple-glass-effect.json"],
    files: [
      {
        path: "registry/example/apple-glass-effect-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/apple-glass-effect-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "apple-glass-effect-demo") };
    }),
    meta: undefined,
  },
  "3d-layered-card-demo": {
    name: "3d-layered-card-demo",
    description: "Example showing a 3D layered card.",
    type: "registry:example",
    registryDependencies: ["https://nyxui.com/r/3d-layered-card.json"],
    files: [
      {
        path: "registry/example/3d-layered-card-demo.tsx",
        type: "registry:example",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import(
        "@/registry/example/3d-layered-card-demo"
      )) as RegistryModule;
      return { default: pickRegistryComponent(mod, "3d-layered-card-demo") };
    }),
    meta: undefined,
  },
  utils: {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/lib/utils.ts",
        type: "registry:lib",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import("@/registry/lib/utils")) as RegistryModule;
      return { default: pickRegistryComponent(mod, "utils") };
    }),
    meta: undefined,
  },
  footer: {
    name: "footer",
    description:
      "A simple footer component i will add some more modern components in the future.",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/blocks/footer.tsx",
        type: "registry:ui",
      },
    ],
    component: React.lazy(async () => {
      const mod = (await import("@/registry/blocks/footer")) as RegistryModule;
      return { default: pickRegistryComponent(mod, "footer") };
    }),
    meta: undefined,
  },
};
